<!DOCTYPE html>
<html>
<head>
    <?= $this->meta->head($meta['head']) ?>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                <div class="pt-4"></div>
                <h1>Login</h1>
                <?php if($error): ?>
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong>
                        Your credentials is invalid or not found
                    </div>
                <?php endif; ?>

                <form method="POST">
                    <?= $form->csrfField('noob') ?>
                    <div class="form-group">
                        <label for="fname">Name</label>
                        <input type="text" name="name" required id="fname" placeholder="Name" class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="fpass">Password</label>
                        <input type="password" name="password" required id="fpass" placeholder="Password" class="form-control">
                    </div>

                    <button class="btn btn-primary">Login</button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <?= $this->meta->foot($meta['foot']) ?>
</body>
</html>